### ISSUE TITLE
Features to investigate

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#105]
Default text widget bindings: https://tcl.tk/man/tcl8.6/TkCmd/text.htm#M192

1. Clicking middle button pastes *selection* (not copy/paste buffer) into text widget

**Comment by srjfoo** [comment]
1a. Investigate simulating middle click for those who use laptops with a trackpad. 😁 

This is actually probably a feature that's not all that necessary.

What I do that is somewhat similar on a Mac is select text, hold down the option key, and drag to where I want the text duplicated. It's duplicated without copying the text to the clipboard. It's not implemented everywhere (doesn't work in Slack or gg2, but does for github comments, google docs, and all the word processors/text editors that I've used on my computer. It's definitely something that I would miss -- it irritates me that Slack hasn't implemented it.

Possibly more to the point, I'd miss being able to select a word or phrase and drag it to a new location (and no, gg1 doesn't do it either).

**Comment by windymilla** [comment]
Closing - if OS supports middle button, then this feature seems to work already - at least on Windows, it does - and if not, then it's harmless to not have it.
