### ISSUE TITLE
init_os_menu() doesn't work as-written on Mac

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#116]
While looking into #115, I ran across `init_os_menu()` in application.py. Based on the below code, I assume the intent is to add an "About Guiguts" item to the Apple-icon menu:

```python
        if is_mac():
            # Apple menu
            menu_app = Menu(menubar(), "", name="apple")
            menu_app.add_button("About ~Guiguts", self.help_about)
            menu_app.add_separator()
```

However, that's not happening:

<img width="266" alt="Screenshot 2024-02-03 at 6 34 46 PM" src="https://github.com/DistributedProofreaders/guiguts-py/assets/294481/304fcfbb-091a-4864-bf52-55f4d849544b">

There is an "About Guigiuts" item under the Help menu, but it doesn't seem to be from this code. I changed the title as a test, and the Help menu item didn't change. That leads me to believe the Help -> About item is a default.

On Mac, you can search menu items (using a search box under the Help menu). So I searched for my modified menu item ("A33bout ~Guiguts"). It does appear in the search result, except it appears to be tied to some sort of invisible menu wedged between the Help and Window menus.

<img width="573" alt="Screenshot 2024-02-03 at 6 38 48 PM" src="https://github.com/DistributedProofreaders/guiguts-py/assets/294481/13e04648-1aab-4c6d-a16a-9e83fa31a2c0">

For reference here's a similar screenshot where I searched for the "Paste" menu item:

<img width="463" alt="Screenshot 2024-02-03 at 6 42 34 PM" src="https://github.com/DistributedProofreaders/guiguts-py/assets/294481/c4aab431-7137-48e7-a608-74eacd85d8d5">

Hopefully that illustrates what I mean. In both screenshots, the "Help" menu is selected (because I am in that menu doing the search), but when you arrow-key down to a result, it also highlights the menu containing that item. In the first screenshot, it's an odd little square that overlaps a bit with the "Window" menu, but in the second screenshot, it's clearly the "Edit" menu.

Finally, I gave that menu a label value which reveals its position:

```python
menu_app = Menu(menubar(), "appltest", name="apple")
```

<img width="527" alt="Screenshot 2024-02-03 at 6 43 56 PM" src="https://github.com/DistributedProofreaders/guiguts-py/assets/294481/dee34d56-0fcb-4998-9035-ddb6fff07c4f">

In any case, it appears this menu does nothing, so I'll plan to send a PR to remove or disable it.

The rest of that function seems to be useful, however:

```python
            # Window menu
            Menu(menubar(), "Window", name="window")
```

When that line is removed, the "Window" menu disappears. So that should certainly remain.

**Comment by srjfoo** [comment]
Side comment: I'm used to seeing the "About <application>" menu item in the application menu, not the Apple menu, but we don't have a `Guiguts` menu, just a `Python` menu.

**Comment by tangledhelix** [comment]
Since I mentioned the existing (default) "About" menu item, here's a screenshot of the window it displays. It appears to be working correctly.

<img width="632" alt="Screenshot 2024-02-03 at 8 43 42 PM" src="https://github.com/DistributedProofreaders/guiguts-py/assets/294481/07062eae-2987-444d-90e4-55fe2290a610">

**Comment by tangledhelix** [comment]
> Side comment: I'm used to seeing the "About " menu item in the application menu, not the Apple menu, but we don't have a `Guiguts` menu, just a `Python` menu.

I agree about this, and I have 2 notes:

1. We have an About item for now, just in a different place (under Help)
2. I suspect when we get to the packaging steps, making a proper Mac app, we might find a way to do it "correctly".

Do you think we should try, or is the one under `Help` good enough? I was thinking about opening issue on it, as a prompt for later when we get to packaging phase. But on the other hand, how often do people even look at "About"... is it worth spending time on it?

**Comment by srjfoo** [comment]
> > Side comment: I'm used to seeing the "About " menu item in the application menu, not the Apple menu, but we don't have a `Guiguts` menu, just a `Python` menu.
> 
> I agree about this, and I have 2 notes:
> 
>     1. We have an About item for now, just in a different place (under Help)
> 
>     2. I suspect when we get to the packaging steps, making a proper Mac app, we might find a way to do it "correctly".
> 
> 
> Do you think we should try, or is the one under `Help` good enough? I was thinking about opening issue on it, as a prompt for later when we get to packaging phase. But on the other hand, how often do people even look at "About"... is it worth spending time on it?

I don't think we need to open an issue about it at this point -- we can punt it off down the road and make the decision later.

Examples: In Firefox, the easiest way I've found to restart after downloading an update is to open "About Firefox", and I expect it to be under the Firefox menu. On the other hand, Slack and BBEdit and many others have "Check for updates" and "Preferences..." under the application menu. And "About" is pretty common, too.

That being said, Mac users who use GG1 are used to a funky interface.
