### ISSUE TITLE
Export/import with page breaks

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#136]
If the PPer makes edits in another editor or similar tool, the "bin" .json file does not get updated, so the page markers stored in the bin file no longer point to the correct places in the text file.

To allow PPer to make use of other editors, add the following features:
1. Add {#png} markers: Adds something like `{#001}` at the start of png 001, `{#002}` at start of png 002, etc. 
2. User saves file in the normal way (which saves its "bin" file too).
3. User makes edits in another editor.
4. Dummy entry so as not to break comments below :)
5. User loads file into GG (which loads the "bin" file, but the page break locations are now wrong). Code detects the `{#png}` markers and updates the page break locations. (Dev note: mark file as edited here, so that new page break locations will be saved to bin file from now on).
6. Remove {#png} markers: Removes the markers from the file.

Notes:

- This seems better than adding full `-----File: 001.png-----` style page break lines, because it does not affect line breaks.

- Assuming the work in the external editor doesn't delete page markers, things like page labels that were set up beforehand will all still be correct once the markers have been read and removed. Only the locations of the breaks need to be updated so everything else in the bin file will remain valid (Dev note: when bookmarks are implemented, they will need a similar `{BM1}` flag).

**Comment by srjfoo** [comment]
Sounds like it would be helpful. As you've noted, at some point, those flags would need to be removed entirely. But at what point? I favor keeping #5 and #6 separate operations, since I'd think that you'd want to keep them as long as the user might be switching back and forth between editors.

**Comment by windymilla** [comment]
Also mentioned in Slack discussion, if this were implemented in GG1 and GG2, users could easily swap between them.

**Comment by windymilla** [comment]
Since GG1 already has the capability of inserting `[Pg nnn]` at every page break, let's start with that syntax to mark the break.
