### ISSUE TITLE
Builtin class "range" is being masked by reassignment

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#137]
Python has a default class `range` ([ref](https://docs.python.org/3/library/stdtypes.html#range)), but in various places we are reassigning to that name and overwriting it with another value. But in other places, we use `range()` also. Possibly they haven't come into conflict so far, but it may be best to use another name so we don't run into a problem later.

```
❯ python3
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> type(range)
<class 'type'>
>>> range = 3
>>> type(range)
<class 'int'>
```

```
src/guiguts/maintext.py:394:    def do_select(self, range: IndexRange) -> None:
src/guiguts/maintext.py:400:        self.tag_add("sel", range.start.index(), range.end.index())
src/guiguts/maintext.py:438:        for range in ranges:
src/guiguts/maintext.py:439:            start = range.start.index()
src/guiguts/maintext.py:440:            end = range.end.index()
src/guiguts/maintext.py:444:            if range.end.row > range.start.row and range.end.col == 0:
src/guiguts/maintext.py:666:        range: IndexRange,
src/guiguts/maintext.py:684:        start_index = range.start.index()
src/guiguts/maintext.py:685:        stop_index = range.end.index()
src/guiguts/search.py:240:        range = None
src/guiguts/search.py:245:                range = sel_ranges[0]
src/guiguts/search.py:248:            range = IndexRange(maintext().start(), maintext().end())
src/guiguts/search.py:249:        if range:
src/guiguts/search.py:252:                range,
src/guiguts/search.py:271:        range = None
src/guiguts/search.py:274:                range = sel_ranges[0]
src/guiguts/search.py:276:            range = IndexRange(maintext().start(), maintext().end())
src/guiguts/search.py:277:        if range:
src/guiguts/search.py:280:                range,
```

**Comment by windymilla** [comment]
Oops - it would be worth checking if I've inadvertently done that for anything else. I don't know if flake8 (or another tool) can check for that.

**Comment by tangledhelix** [comment]
pylint can:

```
src/guiguts/maintext.py:422:24: W0622: Redefining built-in 'range' (redefined-builtin)
```

Although, it ouputs a lot of other stuff, including "line too long" and stuff we would ignore since we're using black. I'll see if I can integrate pylint and quiet down things that don't matter... I'll open another issue on that.

**Comment by tangledhelix** [comment]
pylint's current report for redefined built-ins:

```
❯ poetry run pylint ./src | grep built-in
src/guiguts/maintext.py:422:24: W0622: Redefining built-in 'range' (redefined-builtin)
src/guiguts/maintext.py:466:12: W0622: Redefining built-in 'range' (redefined-builtin)
src/guiguts/maintext.py:702:8: W0622: Redefining built-in 'range' (redefined-builtin)
src/guiguts/checkers.py:23:34: W0622: Redefining built-in 'range' (redefined-builtin)
src/guiguts/checkers.py:64:8: W0622: Redefining built-in 'range' (redefined-builtin)
src/guiguts/application.py:187:8: W0622: Redefining built-in 'help' (redefined-builtin)
src/guiguts/search.py:240:8: W0622: Redefining built-in 'range' (redefined-builtin)
src/guiguts/search.py:271:8: W0622: Redefining built-in 'range' (redefined-builtin)
```

**Comment by srjfoo** [comment]
> pylint's current report for redefined built-ins:
> 
```
❯ poetry run pylint ./src | grep built-in
```
My ignorance speaking, but should you be checking for `builtin`, also (when I run into something that is sometimes hyphenated and sometimes not, depending on the whim of the dev and the sunspot activity, I generally check for both).

**Comment by tangledhelix** [comment]
> My ignorance speaking, but should you be checking for `builtin`, also (when I run into something that is sometimes hyphenated and sometimes not, depending on the whim of the dev and the sunspot activity, I generally check for both).

I just checked, same result. Actually for these tools usually the "correct" thing to grep for is the warning/error code (which would have been `W0622` in this case).
