### ISSUE TITLE
[Future idea] Multiple cursors

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#142]
**(This is a "down the road" idea -- I'm just writing it down here. I don't think we should look at this yet.)**

Assuming tkinter has a way to handle it, multiple cursors could offer a way to make the same edits in multiple locations simultaneously.

Ways to create multiple cursors, seen in other editors:
- Click in multiple locations with a modifier, e.g. opt-click or alt-click in various places to create additional cursors
- From the current position, use a chord (e.g. shift-opt-{arrow_direction}) to add new cursors in a direction (typically only useful for the up and down directions).
- Using the search mechanism, create a new cursor at subsequent positions matching the search input.

Once cursors are active in 2 or more locations, any keyboard operation is reflected in every cursor location. This could be very useful for cases such as add/remove/change for lists, tables, etc. The existing column operations probably cover some of the same uses cases.

Examples:
- Arrow keys or other movements (like Mac emacs-style) moves all cursors in the given direction (until hitting a boundary, then they would stop and stay there)
- Movement-based selection (e.g. Shift-{arrow}, Shift-Ctrl-{arrow}, select-to-next-word, etc ...)
- Text inputs, or deletes

**Comment by tangledhelix** [comment]
A brief Youtube video illustrating the very basics (but there are many more such demos, some lengthy, some short).

https://www.youtube.com/watch?v=-OxaghXWkT4

**Comment by windymilla** [comment]
Notepad++ has something similar: if you do a column select (including a zero-width one), then insert/delete/arrow keys operate on all the rows that the tall cursor covers - the cursor doesn't always show well however.
I'm not aware of a way to show multiple insert cursors, except possibly by coding them manually, maybe with an image that is shown/hidden on a timer.

**Comment by srjfoo** [comment]
Interesting concept. I'm keeping an open mind (and would like to see a concrete example of something where that's the best option). Thoughts that spring immediately to mind:
* I wouldn't want to use it for more than one screen at a time, because I'm paranoid and want to see the changes so that I am aware of what's going on and can abort and back out if I need to.
* I wouild probably be more likely to need a more complex regex s/r.

But yes, definitely not needed right now.
