### ISSUE TITLE
Bundle Jeebies binaries

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#172]
GG1 bundled Jeebies either as a binary (Windows) or as source (all other platforms). This is the original, in C.

DPwiki [claims Jeebies was rewritten in Python][1]; maybe so, but I couldn't find it. The current version used by PPtext seems to be [written in Go][2].

I propose we do as GG1 did, and bundle Jeebies in the ultimate distribution packages (as proposed in #30) for each platform.

A nice thing about Go is that it links statically, there are no dependencies to worry about. Just one executable file.

[1]: https://www.pgdp.net/wiki/PPTools/Jeebies
[2]: https://github.com/DistributedProofreaders/pptext/blob/master/pptext.go

**Comment by windymilla** [comment]
As you say, PPtext is written in Go, although Quentin has just rewritten it in Python for inclusion in Guiguts. I don't know to what extent the jeebies checks in that tool match those in the original jeebies - that would need looking into. If it fully covers what the original did, then we don't really need the original. 

If we do want a separate jeebies tool, I'd much rather it was written in Python than C. There are problems bundling an executable (especially given Windows' and Virus checkers' sensitivities to random executables)

A not so nice thing about Go is that "no-one" (relatively speaking) is familiar with it.

**Comment by tangledhelix** [comment]
I have not thoroughly reviewed pptxt.py, but a quick look at it makes me think it doesn't implement the jeebies functionality. Aside from the fact it doesn't seem to contain any methods / vars / etc with a name suggestive of jeebies, that PR didn't contain the [data file](https://github.com/DistributedProofreaders/pptext/blob/master/hebelist.txt).

I take your point about Go, in any case.
