### ISSUE TITLE
Merged GG2 PPtxt lacks the Levenshtein distance checks that are in the PPWB version of PPtxt.

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts-py#178]
The Python pptxt does not include the Levenshtein distance checks. The comments in pptxt.go indicate that it relies on the creation of a list of 'good words' in the book and a list of 'suspects' that can be compared. The starting point for the 'good words' list is all words in the book minus 'suspects' flagged by spell checking. Python PPtxt does not do spell checking, unlike the PPWB version which uses Aspell.

**Comment by windymilla** [comment]
Thanks - I'll add a "future feature" label to this issue.
