### ISSUE TITLE
Suggestion: Persistent range option for Search-and-Replace

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts-py#179]
In GG1, once a range has been selected and a Search or S&R has been performed, the range is de-selected. There are times when several operations within that range need to be done (e.g., for a long table), so a way of reusing it without having to go through the selection step repeatedly would save time and improve accuracy.

If the most recent range start-end is always stored temporarily, and a "re-use selected range" checkbox was added to the Dialog, that would suffice. That checkbox would be turned off automatically, for safety, after each S&R.

**Comment by tangledhelix** [comment]
An alternate approach might be to add a way to re-select the most recent selection. As an example, Vim and its derivatives allow for this with the `gv` command.

**Comment by windymilla** [comment]
GG1 actually has this feature (see the **bold sentence below**) though I had forgotten about it until @charliehoward4dp entered this issue.

In the status bar, the selected range is displayed. This is either the start & end point of the selection or the number of rows/cols selected (for a column/block selection) - you left-click the label to toggle between those.
If you double-left-click, it pops the selection dialog - I've never used it but maybe someone does.
**If you right-click, it restores the previous selection.**
If you shift-right-click, it restores a column/block selection.

**Comment by charliehoward4dp** [comment]
Thank you, Nigel. Now that I look, that is explained in the manual, and always has been. Maybe I should be the manual sometime.

**Comment by windymilla** [comment]
I'm labelling this "future feature" because it appears virtually no-one knew about its presence in GG1, so it isn't really core. We should do it though.

**Comment by tangledhelix** [comment]
This same "previous selection" behavior is available in GG1 (as a button) in the "Highlight Character or Regex" dialog.

**Comment by windymilla** [comment]
I've started work on this one

**Comment by charliehoward4dp** [comment]
The implementation of this in GG1 does not always remember the most recent selection (I have not been able to find a pattern for this lapse of memory), and in addition, my suggestion is for something that will be specifically remembered by S&R. That way, if someone highlights a big table and must make a series of changes to it, but sees a small error within the table when part-way through that series, the error can be selected and fixed, without losing the S&R selection of the entire table.

**Comment by windymilla** [comment]
> This same "previous selection" behavior is available in GG1 (as a button) in the "Highlight Character or Regex" dialog.

As Charlie mentioned, I found that either awkward or unreliable - so much so I went to look at the code to see how it attempts to work. I suggest waiting to see if what I am implementing in the status bar "selection" button is a more reliable method than the GG1 method.
