### ISSUE TITLE
Consider "Check . lower" and "Check , Upper" checks

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#186]
Currently in GG1's WF dialog, they aren't really WF checks, so haven't been implemented in GG2's WF dialog.

 They could be implemented as normal checks, using the Checker dialog.

Alternatively, if pptxt reports them, maybe they don't need implementing at all?

**Comment by tangledhelix** [comment]
In case it's not already in your mind - these checks are duplicated in GG1; they appear both in WF and in regex.rc under Stealth Scannos. In regex.rc you'll find:

```
,("?\n\s*"?\p{Upper})
,("?\n{2,}\s*"?\p{Upper})
\.("?\n\s*"?\p{Lower})
\.(\s\p{IsLower})
```

**Comment by windymilla** [comment]
Closing, since these are covered by pptxt/stealth scannos
