### ISSUE TITLE
Clear count generated by the search form when a new search is done

### ISSUE THREAD

**Issue by srjfoo** [DistributedProofreaders/guiguts-py#204]
In recent testing, if "Count" is invoked when doing a search, the number is not cleared when a new search is done, so the earlier count persists _**unless**_ "find all" or a new "count" is invoked.

**Comment by windymilla** [comment]
I can't reproduce this:
1. I search for "dog"
2. I click Count
3. It says "5 matches in entire file"
4. I search for "cat" 
5. The message disappears (when I click Search, not when I type "cat")

I must be doing something slightly different, as I don't seem to have to use Find All or Count for the message to be removed.

**Comment by srjfoo** [comment]
> I can't reproduce this:
> 
>     1. I search for "dog"
> 
>     2. I click Count
> 
>     3. It says "5 matches in entire file"
> 
>     4. I search for "cat"
> 
>     5. The message disappears (when I click Search, not when I type "cat")
> 
> 
> I must be doing something slightly different, as I don't seem to have to use Find All or Count for the message to be removed.

Interesting. I hadn't tried it just typing. In the case that triggered opening the issue, I was using the auto-fill-search-field feature. In one case, by opening s/r while the term I wanted to search for was in the main window; in the other, auto-filling from widget results list (don't remember off the top of my head which one). I don't have time for a re-test right now, but I'll do some more advanced testing later today. It may be that it's been fixed, but I'm pretty sure I noticed it again last night (though it may just be because it wasn't fixed in the branch -- I'll do the testing against `master`).

**Comment by windymilla** [comment]
Thanks. I'll give that a try

**Comment by srjfoo** [comment]
* run spell check (test project CTF for 
* `cmd`+`f` to open a s/r dialog with the word `hearted` (specifically looking for words with more than one instance in the file, at least two words with different counts)
* click on Count (shows 6 matches)
* click on `flatteries` in the spell-check list
* `cmd`+`f` to open a s/r dialog with the word `hearted`
* The count still shows the same 6 matches.

This is not inconsistent with the results you had just typing. I think what I'm saying is that, once you open the s/r, either empty or autofilled with another word, the count should clear. Not when you click "search" or "count" or "find all". Once you start another search, the count is no longer valid and should go away. Even if (maybe especially if) the count for the next word turns out to be the same, there should be a clear division between the old and the new.

**Comment by windymilla** [comment]
Got it, thanks. I'll look into that
