### ISSUE TITLE
Status bar mouse clicks

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#210]
Try to make use of Cmd/Ctrl and Shift more consistent with use in checker dialogs.

1. Do we really want "double click" for  "See Img" to choose image dir? I think not - maybe "Cmd/Ctrl" to "process" the image dir might make sense, and "Shift" to toggle Auto Img (Shift meaning "all" when used in checker dialogs)
2. Similarly "Cmd/Ctrl" to "process" page labels, i.e. pop the page label config dialog.
3. Would Cmd/Ctrl-left mouse be better than using right mouse where possible, e.g. in "R:1 C:0"? (I think so)
4. Also, do the clicks need to be "button-release", or would a simple button press do?

**Comment by srjfoo** [comment]
> Try to make use of Cmd/Ctrl and Shift more consistent with use in checker dialogs.
> 
> 1. Do we really want "double click" for  "See Img" to choose image dir? I think not - maybe "Cmd/Ctrl" to "process" the image dir might make sense, and "Shift" to toggle Auto Img (Shift meaning "all" when used in checker dialogs)

The "double-click" feels awkward, so I wouldn't mind seeing something different. Currently, if the image directory isn't linked, and Auto Img is off, that double-click (or shift-click if you change it to that) brings up the open dialog to find the image directory. I really like "Shift" for toggling `Auto Img`.

At one point, I thought there was a menu item for opening the directory with the proofing images in it -- am I mis-remembering?

I'm on the fence as far as using `Cmd`/`Ctrl`+ left click for the purpose of forcing the open dialog. I'm afraid that, at least for Mac users, that might be confusing. (That should not be taken as a reason not to do it, ultimately, but perhaps needs some more thinking.)
 
> 2. Similarly "Cmd/Ctrl" to "process" page labels, i.e. pop the page label config dialog.

Same caveat as above. Given that we already have a strong correspondence between `Ctrl`+ left click and Right-click for Macs, _**and**_ also a strong relationship between `Ctrl` on Windows/Linux and `Cmd` on Macs, I would expect confusion. (And I could also be wrong.)

> 3. Would Cmd/Ctrl-left mouse be better than using right mouse where possible, e.g. in "R:1 C:0"? (I think so)

See above.

> 4. Also, do the clicks need to be "button-release", or would a simple button press do?

What is the reasoning for using "button-release"? Just the ability to back off if you wind up changing your mind mid-click? Is there a clear advantage to "button-press"?

**Comment by windymilla** [comment]
Thanks - that's helpful. I'll put together a PR that simplifies things a bit, and see what you think.
I'm hoping/intendeing to use button-press, not release - reasons for that are lost in history, Perl/Tk, etc.
You're also right that anything available via Cmd/Ctrl click (or similar actions) on the status bar should be available via the regular menus too (maybe with one or two trivial exceptions?).

**Comment by windymilla** [comment]
Found out why it's Button-release. That's what buttons act on normally, so it's necessary to make them behave like normal buttons, and not get stuck in a "pressed" state.
