### ISSUE TITLE
Add Shift to mean "reverse" direction in page labels dialog

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#211]
Clicking cycles round available options. Given that there are 3 options, you need 2 clicks for some changes, e.g. Roman-->Arabic.

If user holds Shift when clicking, cycle in reverse direction so only 1 click is required - this will match behavior of Search and R&S buttons in the S/R dialog (and search in some browsers).

Note: Update or add tooltips for these cases so user knows they exist.

Original issue description:

> Clicking cycles round available options. Given that there are 3 options, you need 2 clicks for some changes, e.g. Roman-->Arabic.
> 
> If user holds Shift or Cmd/Ctrl when clicking, cycle in reverse direction so only 1 click is required.
> 
> For consistency, it would be good if the Search and R&S buttons in the S/R dialog worked the same - they currently do support Shift-click to reverse, but making Cmd/Ctrl also do reverse would mean users wouldn't have to remember which keyboard button to hold when using the feature. It could be argued that in other places, like checker dialog, Cmd/Ctrl means "process" whereas "Shift" means "all", so Cmd/Ctrl makes a bit more sense than Shift for the Search buttons. For consistency with GG1, we want to keep "Shift" working too.
> 
> Note: Update or add tooltips for these cases so user knows they exist.

**Comment by srjfoo** [comment]
Not sure about this. `Cmd`+`f` (find) and `Cmd`+`g` (find again, forward) are pretty standard, and modifying both of them cause it to cycle backwards. When doing a search in a browser window, where there's no text that can be changed, and `return` can be easily used to search forward, and `shift`+`return` to search backwards, `Cmd` on macOS in several browsers either does nothing, or something entirely different (which, I suppose, is a reasonable reason for using it.

But, if `Shift` already works to cause the cycle to go backwards, why also have `Cmd`/`Ctrl`?

**Comment by windymilla** [comment]
I think that's a fair point - I'll edit the description above
