### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#217]
To theme GG2, including dark themes.

- https://ttkbootstrap.readthedocs.io/en/version-0.5/overview.html
- https://github.com/TomSchimansky/CustomTkinter
- https://github.com/rdbende/Sun-Valley-ttk-theme
- https://github.com/TkinterEP/ttkthemes
- https://github.com/RobertJN64/TKinterModernThemes
- https://stackoverflow.com/questions/23836000/can-i-change-the-title-bar-in-tkinter

Apparently the top-level menu bar color cannot be changed in Windows: https://stackoverflow.com/questions/49088785/changing-the-colour-of-tkinter-menubar/49089262#49089262

**Comment by srjfoo** [comment]
Looks interesting.

**Comment by windymilla** [comment]
Some initial work in #233

**Comment by windymilla** [comment]
Notes:
You can change highlight color and background color for the dark & light themes. See `awthemes.tcl` for "helper functions", which you can call using `root().tk.call(command, arg1, arg2,...)`. Some need doing before theme is set up; others can be called after theme is set up, e.g. when theme is changed to dark.

**Comment by srjfoo** [comment]
> Apparently the top-level menu bar color cannot be changed in Windows: ...

I apparently missed this comment first time through. FWIW, the same is true of macOS. The title bar stays dark for a system dark theme and light for a system light theme (assuming that's what you meant?).

**Comment by windymilla** [comment]
Yes, that's right.
