### ISSUE TITLE
Click-drag to select stops at edge of text window on macOS.

### ISSUE THREAD

**Issue by srjfoo** [DistributedProofreaders/guiguts-py#238]
Tested in macOS Sonoma.

Click anywhere in the text window, hold down the mouse button, and scroll (either up or down). The selection is stopped at the edge of the page, and the page will not advance unless the scroll wheel is used in addition (can be mimicked using the trackpad: click-hold-with-thumb and one-finger drag to simulate the click-drag of the initial selection, then two-finger-drage once the edge of the page is reached. (Also, when doing this, you have to twitch the mouse for the selection to show up.

**Comment by windymilla** [comment]
Works OK on Windows

**Comment by windymilla** [comment]
Can you click where you want the selection to start, then scroll to the place you want it to end, then Shift-click there?

**Comment by windymilla** [comment]
Also, do you see this behavior? https://discussions.apple.com/thread/255386688?sortBy=best

**Comment by srjfoo** [comment]
> Can you click where you want the selection to start, then scroll to the place you want it to end, then Shift-click there?

Yes, in gg2. I had to stop and think for a moment, because that doesn't work in gg1 (which I was playing with, for comparison, yesterday).

**Comment by srjfoo** [comment]
> > Also, do you see this behavior? https://discussions.apple.com/thread/255386688?sortBy=best
> 
> I don't know if that exactly describes what I was seeing, but the major part, with the selection stopping at the edge when clicking and dragging, is what I see.
> 
> **_But_** I'm not seeing the behavior described by that post in either Notes or Preview.

Confirmed just now that I'm seeing the same click-drag_to_select-stop_at_edge_of_window behavior under Ventura on an Intel Mac.
