### ISSUE TITLE
Visibility of line of interest

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#244]
When the code shows a line (`see` method) it seems that, at least on macOS, it is happy to have that line at the bottom or top of the screen, rather than in/near the middle. This is not very helpful for the user who wants to see the context around the line.

Dev note: consider calling `see` a few lines above the line of interest, then a few lines below, then the line of interest. "A few" could possibly be half the visible window height, or maybe just a fixed number (10?) would do.

**Comment by srjfoo** [comment]
I just did a quick test, and what seems to happen is that, if there are results following a highlighted result that are visibule within the same "page", the page won't move. Obviously, if the next hit is on the last line, this falls into that category, but the less obvious effect is that if the next hit is few enough lines past the end of the page that re-centering isn't triggered, the page moves up just far enough to put that match on the last line.

I think I've seen it in everything that "finds" a result in the main text window, but for removing page separators, it became much more important to be able to see surrounding context. I may have seen matches at the top of the page, but not very often.
