### ISSUE TITLE
Highlight (single, double) quotes in selection

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#260]
In GG1 Search Menu

@windymilla if you can assign to me, I'm looking into this alongside #41, #42, and #43.

**Comment by tangledhelix** [comment]
In #296 @srjfoo asked about guillemets. I went looking for other quote punctuation and came up with the following.

## Currently highlighted

### Single-quote
- `'` APOSTROPHE
- `‘` LEFT SINGLE QUOTATION MARK
- `’` RIGHT SINGLE QUOTATION MARK

### Double-quote
- `"` QUOTATION MARK
- `“` LEFT DOUBLE QUOTATION MARK
- `”` RIGHT DOUBLE QUOTATION MARK

## Propose to add (guillemets, high/low quote marks)

### Single-quote
- `‹` SINGLE LEFT-POINTING ANGLE QUOTATION MARK
- `›` SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
- `‛` SINGLE HIGH-REVERSED-9 QUOTATION MARK
- `‚` SINGLE LOW-9 QUOTATION MARK

### Double-quote
- `«` LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
- `»` RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
- `‟` DOUBLE HIGH-REVERSED-9 QUOTATION MARK
- `„` DOUBLE LOW-9 QUOTATION MARK

## Unsure

This is a set of "heavy" variants of some of the above items. These seem a bit edge-case to me, but we could include them if desired...

### Single-quote
- `❮` HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT
- `❯` HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
- `❛` HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT
- `❜` HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT

### Double-quote
- `❝` HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT
- `❞` HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT

**Comment by tangledhelix** [comment]
A note for the future. Today these are implemented as menu items, as they were in GG1. But I am thinking that once the dialog for #41 is implemented, maybe all of these highlighter functions can be moved to that control panel. Something like this:

- #41 is a dialog that lets you highlight using a string or regex input
- The 3 menu items from this issue (#260) can become buttons in that dialog
- The 2 modal menu items from issues #42 and #43 could instead be checkboxes in the dialog

As compared to GG1, this would reduce 6 menu items to 1, and concentrate many of these operations into a single dialog which would be a combination of a tool and a control panel for highlighting operations.

In the meantime, depending the order I implement these, I may add a couple more menu items, but they are easily removed later if they move to a dialog.

**Comment by tangledhelix** [comment]
At some point Nigel even suggested we could collapse the 2 buttons / commands from #260 could become a single button which highlights both single & double quotes, but in two different colors.

**Comment by windymilla** [comment]
I still agree that some combining/collapsing would be a good idea. Happy for you to develop it piecemeal of course and sort that aspect out when it's all done.

**Comment by tangledhelix** [comment]
Highlighting quotes together in different colors seems like it would be helpful to identify cases such as `'quoted text"` that could otherwise be missed. It might be a little messy in dialect text, but dialect text is messy in general.

**Comment by tangledhelix** [comment]
I almost wonder about another button that looks only for straight quotes, although they're easy to identify by searching them out. The use case there would be to find quote marks that were not converted by ppmsq or whatever people use to do that conversion in their workflows.

**Comment by windymilla** [comment]
> whatever people use to do that conversion in their workflows.

I would recommend Txt-->Convert to Curly Quotes, followed by tearing off the Curly Quote Corrections submenu to find and fix anything the convertor flags up. Manual description starts here: https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Text_Menu#Convert_to_Curly_Quotes

**Comment by srjfoo** [comment]
> > whatever people use to do that conversion in their workflows.
> 
> I would recommend Txt-->Convert to Curly Quotes, followed by tearing off the Curly Quote Corrections submenu to find and fix anything the convertor flags up. Manual description starts here: https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Text_Menu#Convert_to_Curly_Quotes

I thought tear-offs didn't work for Mac users?

**Comment by windymilla** [comment]
> I thought tear-offs didn't work for Mac users?

A Mac user would have to use the menu in the normal way. An argument for making a small dialog instead of a menu in GG2?

**Comment by srjfoo** [comment]
> > I thought tear-offs didn't work for Mac users?
> 
> A Mac user would have to use the menu in the normal way. An argument for making a small dialog instead of a menu in GG2?

I would think so. Otherwise, if Mac users need to use something repeatedly that Windows users can accomplish more quickly and easily using a tear-off, you're penalizing Mac users for being Mac users.

If it is anticipated that a tear-off would be useful for repetitive processing in general (not just for testing purposes), consider a small dialog instead of a tear-off. Or in addition to, if you have to keep tear-offs for backwards compatibility for long-time users. Wasn't that the general recommendation? Don't do tear-offs; use dialogs instead? (I may have misunderstood.)

**Comment by windymilla** [comment]
Yes, I generally agree with that. But there's no point in penalising all other users, just because Macs don't support a useful feature. So it seems sensible to keep the option of tearoff.

**Comment by srjfoo** [comment]
> Yes, I generally agree with that. But there's no point in penalising all other users, just because Macs don't support a useful feature. So it seems sensible to keep the option of tearoff.

I don't want to penalize anyone, honestly. I was just under the impression that tear-offs have been declared bad practice, in general.

So, I guess the main question is, what are the values of tear-offs that can't provided by dialogs? And if you have to do the dialogs, anyway, why not shift everyone over to using the dialogs (why would it be considered penalizing them)? I'm not against keeping the tear-offs for those who can still use them. I kind of like them and am not sure why they're frowned upon and wish they were available for Macs, from a use-standpoint. Just interested in the reasoning.

(The tear-offs do work on Macs using Perl/Tk/Xquartz, so I guess it did surprise me to learn that they don't for Python/Tkinter.)

**Comment by tangledhelix** [comment]
> I don't want to penalize anyone, honestly. I was just under the impression that tear-offs have been declared bad practice, in general.

As I recall, Nigel implemented them as off-by-default for that reason. I think that's the best approach - some users may really be used to them, and they could potentially turn it back on. Most people probably weren't using them before, and won't now either.

Since they are off by default on all platforms, and unusable on Macs, I do think we should make design choices as though they don't exist, though. So Nigel's statement gives me a bit of pause, as it suggests tear-off is the thing to do for the very common PP task of doing curly quote conversion.

Having tear-off as a defaults-to-off thing for power users who really want it is (IMO) perfectly fine, but since we have chosen off by default, and on one platform they don't work at all, I assert that choices about menu design should be made with tear-off taken out of consideration (even though we all know it's possible to turn them on for 2 of 3 platforms).

We're just discussing in this closed ticket though - perhaps if we want to hash this out more that should happen in a new ticket or in Slack, the forums, etc...
