### ISSUE TITLE
Unicode character entry tools

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#270]
Maybe combine/rationalize what is in GG1 which is:

1. Unicode menu with each block as an entry - pops a  Unicode Block Dialog containing a block of characters (with pulldown to change blocks) - click a character to insert it
2. Tools->Character Tools "Commonly Used Chars"
3. Tools->Character Tools "Unicode Character Entry" - type the dec/hex ordinal and the character is shown & can be inserted in text
4. Tools->Character Tools "Unicode Character Search" - type words from the char name, e.g. "capital greek" and all matching characters are shown. You click one, and it pops the Unicode Block Dialog showing the block (go to point 2)
5. Tools->Character Tools "Compose Sequence" - type keystrokes (or a dec/hex ordinal) to enter any character (e.g. `<"` for left-curly-double-quote)

**Comment by windymilla** [comment]
Point 5 partly done by #280

**Comment by tangledhelix** [comment]
Suggestions:

Item 1 still seems useful but item 2 could just be one page (perhaps the first page in the list?) in that window, collapsing them to one dialog/widget.

Items 3 and 4 could collapse to one dialog with a modal input, e.g.:
- radio button (string, hex, decimal)
- text input box

Depending which option is selected, either behave like item 4 (string) or item 3 (hex, decimal). You could even forego the radio button and try to return valid results for all 3 cases based on whatever the user inputs.
