### ISSUE TITLE
Potential error count improvement for checker dialogs

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#281]
In #277, @srjfoo wrote:

> I don't know if this would be useful in general, or just something that would be useful in testing: since I was seeding errors, and each error I seeded actually caused two or more lines to be marked to be looked at, it occurred to me that it would be nice to have a count of the number of marked lines in the header (say, in parentheses following the count of the number of entries).

In the earlier uses of checker dialogs, it just made sense to count how many entries (with a line.col index), since they were all potential "errors". The recent use for footnotes lists all footnote lines, and only some are "errors", so the above could be a good idea to implement. 

NTS: Will probably need a function passing in that returns True if a line in the dialog is an "error". Or possibly one that returns a code, something like "no count", "count" and "error". Default function would match current behavior, which is "count" for lines with "line.col" at the start and "no count" for others.

**Comment by srjfoo** [comment]
> ... The recent use for footnotes lists all footnote lines, and only some are "errors", so the above could be a good idea to implement.
> 
> NTS: Will probably need a function passing in that returns True if a line in the dialog is an "error". Or possibly one that returns a code, something like "no count", "count" and "error". Default function would match current behavior, which is "count" for lines with "line.col" at the start and "no count" for others.

I probably should have been more explicit in what I was thinking about. Unless it's really easy to differentiate the real errors from the lines that are marked as a result of a different error, why not just tag them all as "possible issues" or "possible errors"?
