### ISSUE TITLE
Add external image viewer

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#294]
Whether we keep the internal viewer or not, we should allow the user to configure an external viewer, like in GG1.

**Comment by srjfoo** [comment]
Granted the current image viewer is a bit rough (specifically that resizing is possible, but choppy and limited in how the resizing is done), I'd like to see it kept. From the Mac perspective, anyway, I have never found a combination that works the way having it built into GG does.

**Comment by windymilla** [comment]
Putting this to one side for now, maybe permanently.
