### ISSUE TITLE
"Configure Page Labels" needs an option to display the selected image

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#295]
Could possibly work by going to the start of that image and using AutoImg? At least as a first attempt.

**Comment by srjfoo** [comment]
Maybe I'm misunderstanding what is meant here, but we can already do that. That is, "turn on `Auto Img`, and use that to navigate to the image for configuring page labels". Or do you mean "have Configure Page Labels turn on `Auto Img` by default, even if it's off"?

If the latter, I have mixed feelings about that. For the most part, I would think that it would be preferred to have the images available, so, it's probably reasonable. I'll defer to others on this.

**Comment by srjfoo** [comment]
Ohhh. Currently clicking on the image name in "Configure Page Labels" doesn't navigate to the image, and yes, that would be useful, instead of having to navigate to it separately.
