### ISSUE TITLE
Some regex replaces aren't working as expected

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#297]
Reported via Slack:

> Tried a search, \b' & replace ’ on a section of dialect.
 "I'd like to
know who'd 'a benn 'er! I wouldn't 'a benn 'er; Ed wouldn't
'a benn 'er; Joe wouldn't 'a benn 'er, and I'd like to know who
would 'a benn 'er!"
I noticed something strange. Originally, the count was 10 leading left curly quotes, but after the change, none were converted to right curly quotes. Even more surprising, the quote count dropped to 0! To double-check, I copied and pasted the section into GG 1.6. My eyes weren't playing tricks on me (the text might be a bit small in GG2, but I assume there will eventually a way for the user to adjust that ).

Also

> I'm trying to replace (\n{3}(?=[A-Z]{2})) with (\n\n.sp 2\n.h3\n). Unfortunately, the search and replace isn't making any changes.

**Comment by tangledhelix** [comment]
`\b` matches `<Backspace>` in Tcl regex ([reference](https://www.tcl.tk/man/tcl8.5/TclCmd/re_syntax.htm#M50))

**Comment by tangledhelix** [comment]
I can replicate the result, `\b'` will match during a search, but replace (with `’`) doesn't actually replace the character. This is in regex mode, of course.

With regex either off or on, a string search for `'` replace with `’` works as expected.

**Comment by tangledhelix** [comment]
This works as well: search `([A-Za-z])'` replace `\1’`

**Comment by windymilla** [comment]
I'll look into it. It's possibly related to a fix I put in so that `\b` matches word-break. IIRC, it's a different character for Tcl, so I sub one for the other. Then when I do the actual replace (which is in python, not Tcl), I may have used the substituted regex by mistake. At least that's a possible explanation.

**Comment by tangledhelix** [comment]
Yes, in Tcl regex `\b` matches `<Backspace>`.

**Comment by windymilla** [comment]
Unfortunately, nothing as simple as fixing my `\b` code - that's "working" as expected. The problem is stuff in the regex that doesn't end up in the match string - `\b` doesn't add any characters to the match string; similarly look-aheads don't work on replacement.

**Comment by windymilla** [comment]
Idea: Would it work to replace leading `\b` with `^` since the string that the replacement is being done must have a word boundary at the start when it appears in context. Similarly use `$` for trailing `\b` or trailing lookahead.
NTS: check you understand why GG1 doesn't have the same bug.
