### ISSUE TITLE
False positives of right single quotes on the Unmatched Curly Quotes Report 

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#312]
The report identified 355 instances of curly quotes that couldn't be matched with their corresponding opening or closing quotes. These are possessives ('s), but the system treats them as unmatched quotes.

Suggestion:

To reduce the number of false positives, consider excluding possessives from the Unmatched Curly Quotes Report. This would focus the report on true mismatched quotes.

Alternative:

If some users must manually review these possessives, then please provide an option to filter or hide them within the report to streamline the process and avoid unnecessary checks for others.

**Comment by G4OEU** [comment]
Thanks for raising this. Can an apostrophe used in a possessive sense be deterministically separated from an apostrophe used in truncation such as in "they're", "you're", etc?

**Comment by okrick** [comment]
The presence of contractions (like "don't" or "we're") in the report is unclear without seeing the actual content.  I didn't find any in the report. There were many names like "O'Connell" in the report.  Content would help the users of the report.

Let's disregard apostrophes surrounded by letters on both sides in this report. This will avoid flagging legitimate uses of apostrophes, including:

    Possessives: Words like "teacher's" or "children's" wouldn't be flagged.
    Celtic name anglicization: Names like "O'Connell" wouldn't be flagged as errors.
    Contractions: Contractions like "don't" or "we're" wouldn't be flagged.

However, this approach will still catch typos where a space is missing after the closing quote. If an unmatched open quote is present without a closing quote, it's likely a typo due to a missing space after the closing quote.

This revised approach focuses on identifying typos while preserving the intended use of apostrophes.
