### ISSUE TITLE
Improve Page Marker Flags

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#316]
At the moment, if you're switching between GG1 & GG2 or vice versa, the Page Marker Flags only cause updating of page break locations, not creation of page break locations. If they also created them, it would further improve the transfer process, because you could delete them in your secondary editor while you do the work there:
1. Add Flags & Save
2. Load into second editor (GG1/GG2 only)
3. Remove Flags & do any type of PPing work
then optionally:
5. Add Flags & Save
6. Load back into first editor
7. Remove Flags & continue working there

**Comment by charliehoward4dp** [comment]
If page marker support is modified, please consider also supporting exchange of page LABEL flags, and using different prefixes, e.g., [Pg 123] for markers and [Pl 123] for labels (the latter is Papa Lima, not Papa One).

**Comment by windymilla** [comment]
Either that, or to reduce the number of additions, we could add the page label after a suitable separator, e.g. `[Pg 123|117]` means image 123.png, page label "117"

**Comment by charliehoward4dp** [comment]
That would be fine.

**Comment by srjfoo** [comment]
Bearing in mind the resistance to change because "That's the way it's done in GG1 and we don't want to upset the current users!", if `Pg 123` is the image name, I would find it less confusing to just have it labeled as such. For example `[Img 123|Pg 117]`. Would No Count pages be labeled `NC`, or something similar?

**Comment by tangledhelix** [comment]
> Bearing in mind the resistance to change because "That's the way it's done in GG1 and we don't want to upset the current users!", if `Pg 123` is the image name, I would find it less confusing to just have it labeled as such. For example `[Img 123|Pg 117]`. Would No Count pages be labeled `NC`, or something similar?

I had the same thought, and didn't post it earlier, but since Sharon said it already... 

No-count seems like it's better to omit the Pg part? Just `[Img 123]` with no label at all?

**Comment by charliehoward4dp** [comment]
This issue may have been initiated as a result of a private message I sent to Nigel. I think we need a way to allow someone using GG2 to easily switch back to GG1 if an insurmountable problem is encountered. Preserving the page breaks, page numbers, and possibly some other Information would make falling back much easier. Once the problem has been circumvented by using GG1, the user could switch back to GG2 if desired. This is only likely to be an issue in the early days following the release of GG2.

**Comment by windymilla** [comment]
Fixed by #330
