### ISSUE TITLE
Starting maximized on Linux, menus are invisible

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#323]
On Ubuntu 22.04 LTS, if Guiguts is started in maximized mode, the menus are not visible. That is, when Guiguts was maximized, and then closed, and reopened, so it starts in maximized mode.

Nothing interesting was logged by `-d` flag. Un-maximizing returns the menus to their proper place (even without a restart).

Screenshot:

<img width="1392" alt="Screenshot 2024-07-11 at 10 46 00 AM" src="https://github.com/DistributedProofreaders/guiguts-py/assets/294481/caf64280-f44d-40e5-a711-baaf74fe8389">

**Comment by windymilla** [comment]
I'll probably have to disable that behaviour on Linux then. User will have to maximise manually, like in GG1

**Comment by tangledhelix** [comment]
Either that or don't memorize maximized as a geometry...
