### ISSUE TITLE
PPtxt Paragraph Spacing Check has a false positive

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#324]
Tools=>PPtxt

```
Paragraph Spacing Check...
5.0:  End point of unexpected 3-line spacing

```

Note this is line 5 and the previous 4 lines were blank.  So this is the end point of a 4-line spacing, not 3-line.

GG1 line spacing check correctly reports this as `4 2`

[766-0.zip](https://github.com/user-attachments/files/16183800/766-0.zip)

**Comment by windymilla** [comment]
Actually, the first line isn't blank - if contains `U+feff` - Zero Width No-Break Space, as you can see if you place the cursor right at the start of the file, and look in the status bar.

As I'm sure you know, this is sometimes put as the first character in a file as a Byte Order Mark. I'm not sure how it got in your file - maybe from another editor?

So, this isn't a bug in pptxt. 

@okrick - do you think that Guiguts should strip out a BOM if it occurs on the first line, or could that be a nuisance for people using a mixture of editors?

**Comment by srjfoo** [comment]
> Actually, the first line isn't blank - if contains `U+feff` - Zero Width No-Break Space, as you can see if you place the cursor right at the start of the file, and look in the status bar.
> 
> As I'm sure you know, this is sometimes put as the first character in a file as a Byte Order Mark. I'm not sure how it got in your file - maybe from another editor?
> 
> So, this isn't a bug in pptxt.
> 
> @okrick - do you think that Guiguts should strip out a BOM if it occurs on the first line, or could that be a nuisance for people using a mixture of editors?

If it's potentially a nuisance for people using a mixture of editors and you don't want to remove it, could it simply be identified in big red letters at the beginning of the file as "Byte Order Mark (BOM)"? My understanding, which is limited, is that the BOM is only necessary for UTF-16 and UTF-32 without the BE or LE specifiers.

(My response to seeing that would be words to the effect of "How on earth did that get there?")

**Comment by okrick** [comment]
Originally, the file was from PG. I used Notepad++ to convert it to UTF-8 encoding, specifically without a Byte Order Mark (BOM). Then, I deleted the PG prefix leaving four blank lines at the beginning.

This raises a potential issue. The software GG2 might be adding a BOM to the file when saving it. This is problematic because PG recommends avoiding BOMs in file submissions.

Ideally, GG2 should automatically remove any BOMs present in the file. This aligns with PG's preferred format for file submissions. See [Byte-Order Marks](https://www.pgdp.net/wiki/DP_Official_Documentation:PP_and_PPV/Post-Processing_FAQ#Byte-Order_Marks)

**Comment by windymilla** [comment]
It's possible GG2 added the BOM, but it seems unlikely, as I've not seen it happen on any other files. 
I've just done a quick test, saving a file, and re-loading it, and there is no BOM.

If you're happy for the BOM to be removed on loading, I think I am too, so I'll do that.

@srjfoo - it wouldn't really be possible to mark it as you said, but I'm happy to remove it anyway.

**Comment by okrick** [comment]
Removing BOMs on loading would be a welcome improvement. It's tedious to constantly open files in Notepad++ just to change the encoding to UTF-8 without BOM. Ideally, GG2 should handle both saving and loading in UTF-8 by default, eliminating the need for this extra step altogether.

**Comment by windymilla** [comment]
Are you saying that GG2 doesn't load files correctly id you just download them from DP? I'm not sure why you need the Notepad++ step. It certainly attempts to load and save in UTF-8 by default - in fact it can't load or save in any other way.
So, if you have a file that is going wrong, there must be a bug in GG2 (or a fault in the file). If you could clarify that, and/or point to a file at DP that I can download and see the problem, I'll look into that issue.

I will definitely remove the BOM anyway, because however it's getting there, we don't want it.

**Comment by okrick** [comment]
While I haven't tested GG2 yet, encountering UTF-8 encoding issues has been a recurring problem with GG1 for as long as I can remember. It only happens with external files, not my own projects. This used to be a common issue with files from sources like PPV reviews and older files from Project Gutenberg (PG) that needed repair.

    Thankfully, PG seems to have transitioned entirely to UTF-8 encoding in the past year or so. I haven't seen any ASCII or Latin-1 encoded files from them recently. While they still occasionally include a Byte Order Mark (BOM) in some UTF-8 files, it appears they're doing a better job of cleaning those up.

**Comment by windymilla** [comment]
Hopefully GG2 will work well for you, especially after I add the BOM-removing code, to cover the case of downloading old files, or PPers who use other editors.

**Comment by okrick** [comment]
Great.  Glad I tested one of my PG errata files.  I'll test it myself once the latest GG2 version is released.

**Comment by srjfoo** [comment]
I'm happy to just have the BOM removed without consultation (probably ought to be documented).

@okrick -- there are still some old CTF files at DP that were generated before we converted to UTF-8. Specifically any projects that were checked out to a PPer before 2020-05-19, but subsequently returned to the pool. I found one, downloaded the CTF, and have confirmed that GG2 did open it and display the characters correctly. The conversion was confirmed, because the file showed as edited upon opening, without me doing anything but opening it. So, even though GG2 doesn't explicitly show encoding, I'm convinced.

**Comment by okrick** [comment]
UTF-8 for the win!  Those days of battling messed-up characters thanks to ASCII, ANSI, Latin-1, etc. are finally over.  While UTF-16 might be on the horizon, fingers crossed the transition is smoother – compatibility can be a headache!

**Comment by srjfoo** [comment]
> UTF-8 for the win! Those days of battling messed-up characters thanks to ASCII, ANSI, Latin-1, etc. are finally over. While UTF-16 might be on the horizon, fingers crossed the transition is smoother – compatibility can be a headache!

Amen!

I forgot to mention above that the file that I downloaded was a very old Portuguese file, with the usual array of accented characters. A run through WF Character Count showed no bizarre characters in place of the expected characters, which was just an additional confirmation.
