### ISSUE TITLE
Load time for large files is excessive

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#327]
GG2 was significantly slower to load this file than GG1 and Notepad++, which both loaded in less than a second. It took GG2 33.4 seconds to load the file.

[dictionary-src.zip](https://github.com/user-attachments/files/16203008/dictionary-src.zip)

**Comment by windymilla** [comment]
Fixed by #330 because it was searching fruitlessly for page marker flags that was taking the time.
