### ISSUE TITLE
The GG2 software shouldn't assume that a `C:\Users\<user>\Documents` path exists.

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#342]
Some Windows users have OneDrive configured, which automatically redirects the Documents folder to `C:\Users\<user>\OneDrive\Documents`. To avoid potential conflicts, it might be better to set the GGprefs location to the root user directory, `C:\Users\<user>`, instead.

**Comment by srjfoo** [comment]
More generally, do we need to allow users to set the location for the GGprefs directory? I know we had this discussion when GGprefs was first implemented for GG1. Being lazy and not looking, the option was to default to the Documents folder on macOS and Windows, and to a dot file in the user directory for Linux? I thought, too, that there was an option to set a different location for Mac and Windows users?

Mac users are afflicted with iCloud. I don't know that it's a direct one-to-one correspondence to OneDrive, but there are various things that you can choose to back up or not. I didn't see the Documents folder as one of them, just sundry apps. iCloud drive can be turned off, though I don't think it can be uninstalled.

**Comment by windymilla** [comment]
I'll look into how easily we can find the Documents folder, wherever Windows in its wisdom tries to hide it.

**Comment by windymilla** [comment]
Fixed by #348
