### ISSUE TITLE
Tools->Jeebies Right Click is same as Shift Right-Click

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#345]
The hover text says:  

> Right click: Remove he/be error from list

> Shift Right click: Also remove all matching he/be errors

Either a shifted or unshifted Right Click only removes the selected he/be error from list

I recommend removing the "Shift Right click" option from the hover text.  Mass replacing "he" with "be" or vice versa is not advisable.

**Comment by windymilla** [comment]
Similar to the basic fixup comments - shifted right click remove matching ones where matching means the error message matches, not just "he" or "be". So, if there are two lines that are the same, and both have the he/be error, then shift with control will fix both of them. Again, it's not going to be a common occurrence.
