### ISSUE TITLE
Tools->Fixup Page Seperators Clicking Auto-fix automatically joins the page seperators

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#346]
The Auto options in GG1 were restricted to influencing "Join" line selections. In contrast, GG2 treats the Auto-fix options selection as synonymous with the "Join" function.

**Comment by windymilla** [comment]
I'm afraid I don't understand the question/problem here. Could you give a specific example, please?

My understanding of 99% auto in GG1 is that it attempts fix all the separators it can, but if it sees a hyphenated word across the page boundary, it has to stop and let the user click Join or Keep Hyphen. My intention is that GG2's auto does the same as that.

**Comment by okrick** [comment]
Simply clicking the Auto-fix radio button caused the action to be taken.  I expected to select the Auto-fix then select the Join action button.

Selecting radio buttons in GG1 does not initiate an action until the desired action is chosen.

**Comment by windymilla** [comment]
Actually, any button in GG1, sets off the auto algorithm. Try turning on 99 Auto in GG1 then just clicking Refresh. You don't need to choose Join

**Comment by okrick** [comment]
GG1 adheres to typical user interface conventions by using radio buttons (<input type="radio">) for selection and a separate button (<input type="button">) for action initiation. In contrast, GG2's radio buttons break this pattern by performing an action directly, which is inconsistent with standard user expectations.

**Comment by windymilla** [comment]
You're right Rick - I thought it was more convenient (i.e. saved a click) but I agree it's better not to do something unexpected like that.
