### ISSUE TITLE
Search and Replace Pop-up has the top of a line of text at the bottom.

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#357]
I can only see the top portion of a message at the bottom of the search and replace box.
The text is cut off and unreadable.

![Capture](https://github.com/user-attachments/assets/39b63d6a-f59d-4ee5-8670-db0bd9dd4009)

**Comment by srjfoo** [comment]
@okrick , can you include an inch or so of area surrounding the S/R dialog in a screenshot? I'm not seeing that effect on macOS.

**Comment by srjfoo** [comment]
Oh, I see. Here's a screenshot of my search dialog pluss a bit of surrounding area:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/5e34a23a-c712-4445-b377-a0e8ae567ad0">

Mine looks a bit different -- the results count is much closer to the bottom of the form.

**Comment by okrick** [comment]
There hidden message was partially displayed below the Results count. I can no longer see it after refreshing the popup. Should I proceed to close this or wait for it to show up again?

**Comment by srjfoo** [comment]
> The hidden message was partially displayed below the Results count. I can no longer see it after closing and reopening the popup. Should I go ahead and close this or wait for it to show up again?

I occasionally see similar in several apps, where what's displayed on the screen is something that isn't really there. I'm not sure what's causing it, whether it's something that's not quite refreshing the screen well enough, or something else. Maybe try a few more times, and if you don't see any repeats, go ahead and close the issue. If you do see it again, try to figure out if there's anything different in the search term than those that don't have the problem.

I'm not sure what to suggest. Maybe @windymilla will have some ideas.

**Comment by okrick** [comment]
Closing.  If some text was hiding then we can resurrect this.
