### ISSUE TITLE
Fix Jeebies "Check Level" radio button behaviour

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts-py#367]
Radio buttons should normally just set an option then separately clicking the "Re-run" button would apply that option and update the display.

The "Check Level" radio buttons of Jeebies currently set the check level required (Tolerant, Normal or Paranoid) and then they do a 'rerun' to apply the change.

Fix the radio button behaviours so that they just set the check level.

**Comment by windymilla** [comment]
Thanks @G4OEU. I previously mentioned Word Frequency as maybe having the same behavior, but having looked at it, I think WF is OK as it is.

**Comment by G4OEU** [comment]
I would note there is at least one exception to the expected behaviour of radio buttons described above. This is the Sort ('Line & Col' or 'Alpha/Type') radio buttons on tool windows which on clicking have immediate effect.

**Comment by windymilla** [comment]
I think the Sort buttons are a little different - they are not re-running the tool, just ordering the results that are already in the dialog.

**Comment by G4OEU** [comment]
OK, I would agree with that more elegant way of distinguishing the behaviour of the Sort radio buttons from other radio buttons.

**Comment by windymilla** [comment]
Fixed by #380
