### ISSUE TITLE
Tools->Word Frequency window does not allow easy navigation

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#374]
GuiGuts 1 offers multiple navigation options within any Word Frequency window, including:

-     Moving to the end or beginning of a list with End and Home keys.
-     Paging up or down with Page Up and Page Down keys.
-     Jumping to the first word starting with a specific letter by pressing that letter.

In contrast, GuiGuts 2 is limited to using the up and down arrow keys plus the scroll bars for navigation.

**Comment by windymilla** [comment]
Temporarily, if you use Tab a few times, it will move focus into the WF list, and you can use page up/down/Ctrl+End/Ctrl+Home

Longer term - I agree, it would be good for some shortcut keys to work in GG2's WF window.

**Comment by okrick** [comment]
Like GG1, GG2 should default to the list upon opening.

Additionally, it's unexpected that clicking within the GG2 WF list doesn't set focus to that list.

Thanks for the tip, I'll use it in the short term.

**Comment by okrick** [comment]
Character key navigation for WF lists is a useful feature.

However, if Python restrictions prevent its implementation, then we'll learn to do without.
