### ISSUE TITLE
Tools-> Word Frequency Ital/Bold/SC/etc - Word Threshold setting does not work

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#375]
Tools-> Word Frequency Ital/Bold/SC/etc - Word Threshold 0 results:
![Capture](https://github.com/user-attachments/assets/515a74b7-2507-499e-b55e-c15bb6f40ce1)

Tools-> Word Frequency Ital/Bold/SC/etc - Word Threshold 5 results (After clicking Re-run):
![Capture2](https://github.com/user-attachments/assets/df591a15-50a4-4771-bd20-2485a0c0df04)

**Comment by windymilla** [comment]
I'm not certain, but I think that is correct. Threshold 5 means that only phrases with no more than 5 words will be shown - at least that's what I wrote in the tooltip :)

**Comment by okrick** [comment]
Given a threshold of 5, it's unexpected that many lines exceed this count. Why is this happening?

**Comment by windymilla** [comment]
It's not like the spellcheck threshold, which means "ignore if this occurs 5 times".
It means a phrase like "<i>this phrase has more than 5 words in it</i>" would not be displayed as an italic phrase. This is the same as GG1, I think, and I guess the reason it was put in was that the tool is to detect where a word (or two) occurs in both italic and non-italic forms, but the user wouldn't want whole sentences that are in italic being reported.

**Comment by okrick** [comment]
Oops. I never utilized the word count threshold other than 0 feature in GG1 and couldn't recall its purpose.  I do now recall raising the issue many years ago.
