### ISSUE TITLE
Tools->Unicode->Normalize Selected Characters should be automatic on opening

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#376]
The 'Normalize Selected Characters' function is counterintuitive. Given the importance of W3C HTML markup validation for PG, it's unclear why character normalization is limited to selections. Ideally, all characters in a document should be normalized automatically upon opening, ensuring compliance with Unicode Normalization Form C. 

GG has already implemented automatic conversion of all documents to the UTF-8 encoding standard mandated by PG.  Unicode Normalization Form C should be no different.

**Comment by windymilla** [comment]
There is a reason it only works on a selection in GG1, which I continued into GG2.
It is described in [this section of the GG1 manual](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Tools_Menu#Technical_note_on_Greek_oxia/tonos)
Perhaps you think the move to GG2 would be a good opportunity to force the hand of all PPers to produce normalized texts, including the controversial Greek characters?

**Comment by okrick** [comment]
Stephen Rowland recommended converting all Greek text to Unicode Normalization Form C (NFC) years ago, prior to HTML5 becoming a PG requirement. I've traditionally relied on BabelPad for this conversion. Recently, I discovered a hidden NFC conversion tool within GG1.

Given that the W3C validator flags non-NFC content as a Warning only, I'm curious if NFC is a strict requirement for PG. 

Additionally, while my observations suggest GG1 and GG2 currently employ NFC, I've read that normalizing entire files is generally discouraged. However, NFC appears safe for use, unlike NFKC which has shown problematic behavior.

By the way, NFC conversion will also convert sequences like U+0061 LATIN SMALL LETTER A followed by U+0301 COMBINING ACUTE ACCENT to U+00E1 LATIN SMALL LETTER A WITH ACUTE.  I don't mind this but others might.

Therefore,  I drop this suggestion.

**Comment by windymilla** [comment]
Thanks Rick - we'll revisit this if necessary in future - the actual code change would be quite simple
