### ISSUE TITLE
GG2 Tools->Unicode>Compose Sequence does not replace the selected character(s).

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#383]
When text is selected in GG1, the generated character substitutes the entire selection. However, in GG2, the generated character is inserted before the selected text, leaving the original text intact. 

Typically, applications overwrite selected text with new input, but insertion occurs only when no text is highlighted.

**Comment by windymilla** [comment]
I noticed this the other day too. Thanks for putting in an issue.
