### ISSUE TITLE
Search->Search & Replace--R & S selects but doesn't highlight next find

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#395]
I used a regular expression `\[\*([^\]\[]+?)\]` to search for `[** Proofers Notes]`. I left the replacement field empty then enabled both 'Regex' and 'Wrap-around' options. 

The first proofreader note was found and highlighted after clicking search. I next clicked 'Replace & Search.' The 1st note was correctly deleted. However, the next proofreader note found was unhighlighted. Despite not being highlighted, clicking 'Replace' deleted the 2nd note, indicating that the 2nd find was selected despite the lack of highlighting.

**Comment by windymilla** [comment]
Sorry Rick. I know exactly what caused that - me!
