### ISSUE TITLE
Duplicate Search & Replace Windows

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#401]
It might be better to avoid opening multiple Search & Replace windows using Ctrl-F.

![Capture](https://github.com/user-attachments/assets/17a23818-d2e2-433a-9bf8-436a44854a74)

**Comment by windymilla** [comment]
@okrick - that shouldn't be possible, and I can't reproduce it. Do you know what you need to do to make it happen, please?

**Comment by okrick** [comment]
The issue seems to have disappeared for now. I'll continue troubleshooting throughout the day and tomorrow. If I can't reproduce it, I'll close this case.

**Comment by windymilla** [comment]
OK, thanks.

**Comment by srjfoo** [comment]
It just occurred to me (and I don't know if this is what caused it for @okrick), that if, as I often do for testing, I have multiple instances of GG2 open at one time, I will get one S/R dialog per instance. But, no, I don't think I've ever gotten more than one S/R per instance for GG2, either.

What I'd really like is some way to tell one instance from another, but I decided not to ask for that. 🤣

**Comment by windymilla** [comment]
Well one easy way would be to use a different theme on your second instance, @srjfoo

**Comment by windymilla** [comment]
It doesn't appear as though this is reproducible, so I'm going to close - we can always reopen if it rears its head again.
