### ISSUE TITLE
Tools->Basic Fixup Ctrl-Left Click causes error

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#402]
Selecting any line in Basic Fixup then Control Left Clicking gives an error.  
![Capture](https://github.com/user-attachments/assets/1ce722b3-f872-46c3-ab79-a97eeefe1a72)

[shipwrecked-utf8.zip](https://github.com/user-attachments/files/16738030/shipwrecked-utf8.zip)

**Comment by okrick** [comment]
I also get the same result with a Control Right click

**Comment by srjfoo** [comment]
Just checked with the `Cmd` key for macOS, and, same.

**Comment by windymilla** [comment]
Thanks @okrick - I can reproduce it - I'll get a fix sorted out.
