### ISSUE TITLE
Hover text disappears after one action in any of the Tools menu popup windows

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#403]
The current behavior of the hover text is inconvenient. It currently disappears forever after any single click combination. It would be more user-friendly if it remained visible until intentionally dismissed, allowing for repeated reference. This applies to the Basic Fixup, Word Frequency, Spelling, and any other tool that utilizes a similar popup window.

**Comment by srjfoo** [comment]
That's not the way tooltips work. They actually disappear (at least for me) for most things, as soon as I move the mouse (for instance, when looking at an xkcd comic). In GG2, I actually have to move the cursor outside the results box, or click on something, to make it disappear. If I move the mouse outside the results pane and then back in again, it reappears. Can you check to see if that works for Windows as well as for macOS?

**Comment by okrick** [comment]
I may have misdescribed the issue. In Windows applications like Notepad++, hover text appears when the cursor hovers over a screen element. It disappears when the cursor moves outside the element or when the element is clicked or selected. The tooltip reappears when the cursor returns to the element's zone or, in the case of a selection, when the cursor moves outside the zone and then back.

After further investigation in GG2, I understand the behavior. The entire popup is the trigger for the hover tip, not just a specific element. So, when I interact with the popup, the tooltip disappears as expected, but I must move the cursor outside the popup's boundaries for it to reappear. Typically, the trigger for a hover tip is a smaller element, like a button. My assumption that the trigger was the line I was hovering over was incorrect.

To add to the confusion, the hover tip in GG2 appears after a significant delay of about three seconds. In Notepad++, the delay is less than a second.

I have two questions:

1. Can the hover tip trigger zone be limited to a specific line?
2. Can the time delay be shortened to approximately half a second, which is closer to what I believe Notepad uses?"

**Comment by windymilla** [comment]
Thanks Rick - I've added an issue about making help available, and considering the "re-pop tooltip" idea: #404
