### ISSUE TITLE
Font size changes not reflected immediately on macOS

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#408]
As described in this comment:

> If I resize the text while the Unicode Block dialog is in front (actually, any widget, including the Settings widget), the text in the text window is resized immediately, as are the line numbers, and the main window line height is adjusted, but the line height for the line numbers is not adjusted until the main window is brought to the front. Unicode block characters on the buttons don't change size until the window is brought to the front (actually, all of the widgets will adjust at the same time -- if I resize and go to s/r and type something in and hit return, the unicode block sizes will adjust too.

**Comment by tangledhelix** [comment]
At least the line-height for the line numbers, as described above, seems to have been fixed along the way somewhere. The other behaviors are still present.

**Comment by windymilla** [comment]
@srjfoo & @tangledhelix - are you happy for this to be documented in the manual and then closed. It appears the Mac requires the dialog to become focused before it will be updated. The only other option I can think of would be to maintain some kind of list of all the visible dialogs and either temporarily give them focus & update them, or maybe just an update for each would be sufficient?

It's a pretty rare thing for a user to change their font size, and even rarer to do it while also doing other work involving a dialog

[_whisper_: and it's only Macs]

**Comment by tangledhelix** [comment]
I'd agree people probably don't change fonts very often. I'm fine with it.

**Comment by srjfoo** [comment]
I'm fine with it, too.

Should there be/is there a "known issues" section of the manual. I would think that would be a good place to document such things -- that way, you don't have to search the whole document if you're looking for that information.

**Comment by windymilla** [comment]
> Should there be/is there a "known issues" section of the manual

There is now: https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_2_Manual#Known_Issues
