### ISSUE TITLE
regex special character $ works differently in GG2

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#419]
I attempted to use the regular expression `(\d+)$` to locate and replace page numbers in my table of contents using GG2. However, GG2 indicated no matches.   Is GG2 interpreting new line characters as part of the string?

This expression works successfully in Notepad++ and GG1.

**Comment by windymilla** [comment]
Thanks for the report, @okrick
Sorry about that. I did some work on making `^` work correctly for beginning of line (I hope) but it looks like I overlooked `$` for end of line.
As you suspected, for now, you could use `(\d)\n` for your search string, as long as you remember to put the `\n` on the end of your replace string too.
I'll look into fixing it as the next thing I do.

**Comment by windymilla** [comment]
Actually, @okrick, a better solution is to replace `$` with `(?=\n)` (i.e. lookahead to see if there's a newline next). That way, the newline character is not included in the match, just like with `$`, so you won't need to add it to your replace expression.
