### ISSUE TITLE
Highlight surrounding quotes/brackets

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#42]
In GG1 Search menu

**Comment by tangledhelix** [comment]
I'm looking into this.

**Comment by tangledhelix** [comment]
The Perl implementation of this comes from the Perl TK module, it's not our own code. So far I haven't found a similar function in tkinter, so most likely I'll port the Perl code and make it part of the GG2 codebase itself.

See `HighlightSinglePairBracketingCursor` function defined here (starting on line 432 as of this writing):

https://metacpan.org/release/SREZIC/Tk-804.036/source/Tk/TextEdit.pm
