### ISSUE TITLE
Update the "supported" Unicode blocks list

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#421]
Use http://unicode.org/Public/UNIDATA/Blocks.txt
combined with top answer here: https://stackoverflow.com/questions/243831/unicode-block-of-a-character-in-python
or possibly the bottom similar answer.

This will give ALL unicode blocks. Do we want to hide some from the Unicode Block dialog and/or the Unicode Search dialog?

**Comment by windymilla** [comment]
Also potentially useful is the 3.2 blocks list: https://www.unicode.org/Public/3.2-Update/Blocks-3.2.0.txt

**Comment by srjfoo** [comment]
> This will give ALL unicode blocks. Do we want to hide some from the Unicode Block dialog and/or the Unicode Search dialog?

The list doesn't look nearly as overwhelming in this form in GG2 as it does to me in GG1, so I have no strong feelings one way or the other (though there are a lot there that don't look useful). One thing that many apps have (I don't know if it would be easy to implement or whether it would be worth it in a different PR) is the ability to navigate open menus by typing the first two or three letters. This does not appear to be default behavior for all menus, though. Although it works in the app level menus (i.e. the menubar) for me for GG2, it doesn't work for the widget.
