### ISSUE TITLE
Replace invalid syntax error message

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#422]
Searched for `\n\n(<sc>[^\n]+)(?=\n.pm poemend)`
Replaced `\n\C" "x(82-length("\1"))\E\1`

Error message:
![Capture](https://github.com/user-attachments/assets/4a407786-8d54-4a9c-9177-7c3f560295eb)

File:
[country.zip](https://github.com/user-attachments/files/16912959/country.zip)

Are \C and \E not yet implemented?

**Comment by windymilla** [comment]
Yes, but they take python not perl.
Should the x be an asterisk, and length should be len? Not at computer so can't check myself. It's late here.

**Comment by okrick** [comment]
This is straight from the [Regex Cookbook](https://www.pgdp.net/wiki/Regex_Cookbook#Right).  

It works using an asterisk and len instead of length.  So I'm closing this.

We'll need to update the Regex Cookbook.

**Comment by windymilla** [comment]
Thanks Rick - I'll have a look at the cookbook, and for now at least add a comment, even if they don't all get updated immediately

**Comment by windymilla** [comment]
Done
