### ISSUE TITLE
Highlight Alignment Column

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#43]
In GG1 Search menu

**Comment by tangledhelix** [comment]
I'm looking into this.

**Comment by tangledhelix** [comment]
Key bind note: the GG1 key binding for this is `Ctrl+Shift+a`, suggesting a Mac key bind of `Shift-Cmd-a`. Just a note to check into this later: on my Mac, this keystroke, when invoked in a text control (such as the GG2 editor window), calls the `Search man Page Index in Terminal` system service. I don't believe I activated that, so I believe it may be a default binding. Also need to check whether a keybind we set would override it, or if the system service would take precedence.
