### ISSUE TITLE
Implement an automatic table generation feature in HTML

### ISSUE THREAD

**Issue by Imran-imtiaz48** [DistributedProofreaders/guiguts-py#472]
Add functionality to automatically generate and format tables in HTML, streamlining the process of creating structured data layouts.

**Comment by windymilla** [comment]
Hi @Imran-imtiaz48 - thanks for adding this issue. Is there something specific you were thinking of that is not covered by [this (somewhat brief) issue](https://github.com/DistributedProofreaders/guiguts-py/issues/449)? That one is a shorthand for "add a feature like Auto Table in the HTML Markup Dialog of Guiguts 1".

Are you already a PPer at DP, and/or already familiar with the [Guiguts 1 tool](https://github.com/DistributedProofreaders/guiguts)? There are quite a few features that GG1 has, that have not yet been implemented in GG2. The planned order of development is to get GG2 to the point where a PPer can create and check the text version of a book, and only then will the features to generate and check HTML be added.

**Comment by windymilla** [comment]
Duplicate of #449
