### ISSUE TITLE
Spell check not highlighting word correctly when preceded by quote

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#477]
> If I click on a spelling check query result for a word preceded by a quote mark, the preceding quote mark is highlighted in the main window as well as most of the word but not the last character of query so "''Tis" at start of line, "'Tis" was listed in spelling check results and "''Ti" was highlighted in main window. I've used "'Tis" as an example but it happens for words that don't have an apostrophe at the start as well.

**Comment by srjfoo** [comment]
I've done a little poking, and at least for me, this is limited to single quotes/apostrophes. Double quotes do not seem to have the problem.
