### ISSUE TITLE
Paste doesn't overwrite selected text

### ISSUE THREAD

**Issue by noystergithub** [DistributedProofreaders/guiguts-py#494]
Select some text and copy or cut
Select some text elsewhere, intending to overwrite that text
Paste - pasted text doesn't overwrite selected text as expected, but sits beside it
Same whether using the Edit menu or Ctrl-X or C then Ctrl-V.

**Comment by srjfoo** [comment]
What version of GG2 are you using? There was such a bug, but it was fixed. It works for me in alpha9.

macOS Sonoma.

**Comment by noystergithub** [comment]
Sharon,
 
I only installed GG2 a week ago. The top bar has “Guiguts 2.0.0a9”. 
 
I'm on the dreaded Linux (Ubuntu 24.04.1).
 
Neil
 

On Tuesday, October 08, 2024 18:17 BST, Sharon Joiner ***@***.***> wrote:
 
What version of GG2 are you using? There was such a bug, but it was fixed. It works for me in alpha9.
macOS Sonoma.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/DistributedProofreaders/guiguts-py/issues/494#issuecomment-2400419277", "url": "https://github.com/DistributedProofreaders/guiguts-py/issues/494#issuecomment-2400419277", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by srjfoo** [comment]
Thanks -- it's helpful to have OS and version information. You would not believe how many Mac-only or Windows-only problems we've run into. No reason why there can't be Linux-only problems, too.

**Comment by srjfoo** [comment]
> There was such a bug, but it was fixed.

My bad -- Nigel said that it was a different bug that was fixed. And what I'm seeing is likely default behavior on Macs.

**Comment by windymilla** [comment]
@noystergithub - I have been able to reproduce it on my WSL setup (Linux on my Windows machine).
I agree it would be good to make the Linux version behave like the Windows & Mac versions, although I believe the behavior you are seeing is in fact the default behavior for X-based programs on Linux. If you have any other X-based programs you may be able to confirm this.
