### ISSUE TITLE
Highlight cursor line

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#522]
The line number (in the left-hand gutter) is highlighted for the current line. I suggest highlighting the line of text itself, as is somewhat commonplace these days in code editors. It would need to be a subtle highlight, and pushed to the bottom of the tag stack so it doesn't interfere with any other tags.

(And potentially be configurable as not every PP'er may want it to be turned on?)

A few examples from Visual Studio Code attached. I'm thinking of something like a pale blue or very light gray background in light mode, and a dark gray (lighter than the background, though) in dark mode.

<img width="668" alt="Screenshot 2024-11-11 at 12 38 30 AM" src="https://github.com/user-attachments/assets/87716df5-d4fa-4ca2-95b9-975aa7b9794a">
<img width="602" alt="Screenshot 2024-11-11 at 12 39 53 AM" src="https://github.com/user-attachments/assets/76afa430-67af-4050-86c6-2abbab4c3f92">
<img width="597" alt="Screenshot 2024-11-11 at 12 39 33 AM" src="https://github.com/user-attachments/assets/a257a6f7-5d0c-4946-becb-ff9365b6ec0a">

@windymilla I plan to look at this one.

**Comment by srjfoo** [comment]
Something that @windymilla said just clicked. On a Mac, when the system is in dark mode, the default theme is dark. Apparently on Windows, it's light, regardless of what the OS is. So, for it to appear correctly on both platforms (don't know about Linux), `is_mac` may be necessary. A dark grey that is lighter than black might not show up very well on the default theme on a Mac if the system is in dark mode. Light shouldn't be a problem, I'd think.

**Comment by windymilla** [comment]
@tangledhelix - I don't know if `maintext().is_dark_theme()` would be any help in deciding about colors. The docstring says

> """Returns True if theme is dark, which is assumed to be the case if the brightness of the text color is greater than half strength (mid-gray)."""

This means it does not depend on the name of the theme being "dark" or "light", and it will cope with the Mac case of following the system theme when using the "default" theme.

It is currently used in 2 places: to choose a suitable "red" to indicate that a regex in the S/R search field is bad; and to adjust the transparency of the image viewer (to let some of the background color show through and stop the image being too starkly black & white).

**Comment by windymilla** [comment]
> (And potentially be configurable as not every PP'er may want it to be turned on?)

I suggest not making it configurable unless PPers make a fuss.
