### ISSUE TITLE
Refactor _highlight_configure_tag to use is_dark_theme

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#532]
As discussed in #525, consider updating `_highlight_configure_tag` to use `is_dark_theme` to auto-detect light/dark when calculating what colors to apply.

Potentially this would simplify a few things, including perhaps not needing to define a "Default" value in the color maps at all, and using only "Light" and "Dark".

**Comment by windymilla** [comment]
Yes - I think this is a good idea
