### ISSUE TITLE
Fix errant 1.0 highlight in "highlight alignment column" mode

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#545]
As reported by @srjfoo in review of #544:

----------

I don't know if this is something you want to fix or not, but I assume it's unintentional:

<img alt="image" width="200" src="https://private-user-images.githubusercontent.com/36800239/390272415-58908cae-50bc-49b9-a8d6-a1f7d0b29a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTA0ODMsIm5iZiI6MTczMjY5MDE4MywicGF0aCI6Ii8zNjgwMDIzOS8zOTAyNzI0MTUtNTg5MDhjYWUtNTBiYy00OWI5LWE4ZDYtYTFmN2QwYjI5YTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA2NDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjgzM2M3MDg1NGViNDc0ZGY0NTA0OGZhZTQ1ZmY2N2Y0MWNkMTcxOWMwOTBhYzU0OTQ2ZWJhYjAwZTA4MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xGboD-Hj3CAQUItY2SiHqCaJ1fiNCK65WowJjDHIhQY">

PPers won't even notice it unless there's a character in line 1, column 1 (which there was for one of my test files). Unless the cursor is at column 0, of any line, L1, C1 is highlighted, along with the column following the cursor position.

Which brings me to the next point, which, I think, is related to how the cursor position is identified.

If the cursor is positioned preceding column 1, the status bar identifies that as c0. The cursor column position is (and I believe has been, traditionally?) identified in GG by the character preceding it. That is, if the cursor position is at L:14 C:0, the cursor is positioned before the first character on line 14, and if C=1, then it is following the first character on the line.

In this particular case, if C=1, it is actually column 2 that is highlighted. **_EXCEPT_** that if C=0, column 1 is not highlighted.

It's entirely possible that there's no good reason fot column 1 to be highlighted, but, as with L1,C1 being highlighted when alignment column >1, if there's text there, it's an inconsistency.

At least on default/dark, the highlight color for straight double quotes is either the same as the color for the column alignment highlighting, or very close. (I'd take the latter a bit darker, maybe?) Again, it may not be worth worrying about, but I thought I'd mention it.

**Comment by srjfoo** [comment]
> unless there's a character in line 1, column 1 (which there was for one of my test files). Unless the cursor is at column 0, of any line, L1, C1`[** character 1]` is highlighted,

**Comment by tangledhelix** [comment]
This was caused by `MainText.get_screen_window_coordinates` returning row 0 as the earliest possible row in the file. The highlighter was trying to highlight `0.{col}`. Since that didn't exist, it highlighted the nearest character it could fine, which was `1.0`.

Looking at the GG1 code, I didn't port it exactly the way it worked before, so this is just a regression bug.
