### ISSUE TITLE
Illegal language settings permitted & then causing error

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#546]
As described [here](https://www.pgdp.net/phpBB3/viewtopic.php?p=1353243#p1353243) it appears the user can set the language to "English", which is actually an illegal language code. Language codes should contain lowercase letters and maybe an underscore.

**Comment by rtonsing** [comment]
I don't remember ever setting it, I definitely didn't edit the json.

**Comment by windymilla** [comment]
Thanks @rtonsing - I've put up a fix for it, which should get checked & merged in the next few days.
