### ISSUE TITLE
"Highlight alignment column" behavior with active selection

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#554]
Another case of "what do we do when there's a selection?"

The alignment column is chosen based on the insertion point. As with the other cases we've seen, that might be at the end of the beginning of a selection (or it's even possible to end up anywhere within the selection).

And in a columnar selection, the cursor might end up at any of the 4 corners depending on how the selection was made.

Do we just live with wherever the cursor is (in other words, do nothing)? Decline to activate this mode while a selection is active?

(For what it's worth, GG1 takes the approach of setting the column based on the cursor wherever it happens to be, selection or no.)

**Comment by windymilla** [comment]
I think that's OK. I think anyone would do that deliberately. They position the cursor, then turn on column highlight. It's different to the quote/bracket highlighting which is dynamic and so should show something sensible even when you make a selection.

**Comment by tangledhelix** [comment]
Yes, makes sense. And it's what GG1 did and nobody has (to my knowledge) complained about that. Will close.
