### ISSUE TITLE
"Enable Scanno Highlighting" mode

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#560]
In GG1, Preferences / Appearance / Enable Scanno Highlighting.

**Comment by windymilla** [comment]
Do we want this, or is it just because it is in GG1?

**Comment by tangledhelix** [comment]
I added this issue because it's in GG1 and in my own PP workflow. Thinking for a bit about my history with it, it hasn't been all that useful for me. I can't think of a time it caught anything, and I suspect everything it knows is already in the Stealth Scanno tool. I'm just as happy to close it, in light of that...
