### ISSUE TITLE
Image dock request: would like buttons to navigate to previous or next page.

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts-py#567]
It is awkward to find where to click in the text pane to see another page, and after a file has been extensively reformatted to move illustrations and footnotes out of paragraphs, sometimes it is impossible to view particular pages.

**Comment by srjfoo** [comment]
Do the `<` and `>` in the status/toolbar not work?

<img width="243" alt="image" src="https://github.com/user-attachments/assets/36b8b414-4873-4d1e-a07c-84819858bddc">

**Comment by rtonsing** [comment]
Duh, yes!
