### ISSUE TITLE
Consider rectangle at top left of main text

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#575]
On Windows with GG2 Light or Dark theme, the color of that rectangle, visible only when both line and column numbers are visible, is slightly different to the background color of the line & column number widgets - see screenshot.

1. Is it better to have it slightly different in order to show the boundary of the line & column numbers?
2. If so, should it be different for Default theme (it isn't on Windows)?
3. If not, should we make it the same?
4. OR, should/could we use that rectangle for something else useful? Difficult to think what that might be - if it were a button, you would only see it when both line & col numbers were visible. Maybe a button to turn on/off the vertical align highlight? Or some other idea?

![image](https://github.com/user-attachments/assets/80e28b4f-19db-4c13-b81a-01d0ca3d23f4)

**Comment by srjfoo** [comment]
😆 -- or 

5. Is it something we need to worry about at all?

In default, that corner shows no difference on macOS, either, but I don't know that it's something that needs a solution.

**Comment by tangledhelix** [comment]
There's nothing there, so what's coming through is the background color of the root window, I assume. As @srjfoo points out, in some themes (like Default on Mac) they don't actually differ. In both Dark and Light theme they do differ (on Mac), and clearly it differs on Windows.

For me at least, it isn't only in the upper left corner.

- Both rulers off: lower right
- Line ruler only: lower left, lower right
- Column ruler only: upper right, lower right
- Both rulers on: all 4 corners

Screenshot below which shows all 4 corners. They all appear to be the same color (#272B2D) according to my color meter app.

<img width="418" alt="Screenshot 2024-12-16 at 10 45 38 PM" src="https://github.com/user-attachments/assets/793c41c9-3e68-4c83-a5f0-2491d2553951" />

In any case, I can't imagine what would go there... I could imagine making it the same as the ruler background color, but then something probably needs to be responsible to keep that up to date with the theme. And I might want a thin border to define the ruler's edge, in that case.

**Comment by tangledhelix** [comment]
> And I might want a thin border to define the ruler's edge, in that case.

If we care about this, it is worth thinking over a bit, since at least on Mac Default theme (and maybe other platforms; I'm not sure), the background is currently uniform between the two rulers and this rectangle. So right now there is no defined edge to the ruler, and it's worth a moment to think whether we should add one.

(I could go either way.)

**Comment by windymilla** [comment]
Consensus seems to be to leave it (at least for now) so closing
