### ISSUE TITLE
astroid 3.3.7 has been yanked

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#599]
On my latest `poetry install`, I got this warning:

> Warning: The file chosen for install of astroid 3.3.7 (astroid-3.3.7-py3-none-any.whl) is yanked. Reason for being yanked: Creates crash with cryptography module in pylint

**Comment by windymilla** [comment]
Do you know if we need to do anything about that? And if so, what?

**Comment by tangledhelix** [comment]
> Do you know if we need to do anything about that? And if so, what?

Based on their releases info, I think we should just set it to 3.3.8. The 3.3.8 release is just to replace 3.3.7 because the change in 3.3.7 didn't actually work.

https://github.com/pylint-dev/astroid/releases
