### ISSUE TITLE
Footnote Check Results order

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#607]
I was initially confused about the non-functionality of the `Prev. FN` and `Next FN` buttons. However, I discovered that I needed to locate the footnote section within the very long list. I believe the most logical order for the list should be:

1. Footnote Errors: This ensures immediate attention to potential issues.
2. Footnotes.
3. Anchors.

**Comment by srjfoo** [comment]
Up at the top of footnote fixup, you can sort by line and column, or alphabetically. Alpha sort essentially sorts anchors first, continuation second, errors third and footnotes last, and within each section, by line number. (I think -- my testing example just now does not have any errors, so I am only presuming that errors would be in the third section)

You can also use the "suspects only" checkbox to filter out all of the non-suspect stuff:
<img width="785" alt="image" src="https://github.com/user-attachments/assets/5585d539-e964-42ca-8ace-91251f953a21" />

I've tried that a few times, but I find that I actually prefer the line/column sort. Yes, it's a good idea to know how many you need to be concerned about, but I find that I like seeing them in context. I often check placement  of footnotes and anchors visually, and for that, line/col sort works best, even with a really long list of footnotes and anchors.

**Comment by okrick** [comment]
I agree Line & Col is the better sort for the Footnotes.  

This issue may be closed.

**Comment by windymilla** [comment]
Thanks Rick - we'll continue to monitor as more people begin to use the newly-added Footnote Fixup in GG2.
