### ISSUE TITLE
Word Frequency cursor positioning

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#630]
In GG1, one could right-click on an item in the list and have a search term for that item appear. This functionality is not currently available in GG2.

If that is not possible in GG2, an alternative might be to have the entire highlighted item selected in the text window. Then, all one needs to do is click `ctrl-f` for the item to appear as a search term. Currently, a blank search window appears because nothing is selected—the cursor is simply positioned at the beginning of the highlighted term.

![Capture](https://github.com/user-attachments/assets/1121b192-0ad7-4bae-8d1f-07592a9cb351)

For example, if I wanted to replace all or most instances of `day light` and `day-light` with `daylight` then I could easily select one of the first two lines and then press `ctrl-f` to have a search window with either `day light` or `day-light` appear.  If the entire item can be highlighted then I think it should be relatively simple to include the entire highlighted area as the selection.

This concept might be helpful for any of the WF checks.

**Comment by srjfoo** [comment]
@okrick -- bearing in mind that I'm working on a Mac, I can cmd-left-click on a term in a WF results window, and it is brought up in a search window. I suspect that it's ctrl-left-click on Windows, but try hovering over the results window. There should be a tooltip. If that's not what you mean, my apologies.

**Comment by okrick** [comment]
Sorry, I just realized that I could do that.
