### ISSUE TITLE
Auto Img can cause loop

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#70]
If Auto Img is trying to load an image but can't find it, it pops a directory selection dialog. If the users cancels this, it just pops again.
One solution would be turn off Auto Img if user cancels dir selection.
Another would be not to pop the dir selection at all if because of Auto Img, but that would require the user to manually select the folder.

**Comment by srjfoo** [comment]
I can imagine a situation where there's one image missing out of a set. That is, other images are there, but that one is missing, and the directory is set correctly.

So, I see two main cases:
* The directory doesn't exist
* The directory exists, but the image requested within the directory doesn't exist

Do both need to be taken into account, or just treat them both the same?

**Comment by windymilla** [comment]
When PPing, all images should exist - if not, you need to go and find out why.
I think it would be sufficient that if the user decides "I can't fix this" so Cancels the dir selection, it doesn't just pop up again. However, if they try to view the image again (maybe they've moved a file or the whole dir) and the image can't be found, then it does need to pop the dir selection again.
What I'm saying is that it can't just remember "Oh, I've asked for a dir once and didn't get one, so I won't ask again" because it can't know what the user has done behind its back.
So, I think a safe option would be to turn off Auto Img if user cancels dir selection.
