### ISSUE TITLE
Allow only one instance of dialogs requiring user input

### ISSUE THREAD

**Issue by srjfoo** [DistributedProofreaders/guiguts-py#75]
Currently, if a user opens a "Save as ..." or "Open ..." dialog, gets distracted and when they return don't notice that the dialog is already open, an try to open a new one, a new one opens quite nicely! It works properly, in that once the input is done, and the action takes place, all of the open dialogs are closed, but it's probably still not a good idea to have multiple windows open at the same time. Screenshot:
<img width="806" alt="image" src="https://github.com/DistributedProofreaders/guiguts-py/assets/36800239/e0a583df-9fd9-4217-8d1a-dd737b7e03b5">

This is on macOS Monterey, 12.7.2.

**Comment by windymilla** [comment]
On Windows, the dialog is "modal", i.e. you can't do anything else in GG until you have closed the dialog. I'm guessing that isn't true on macOS. Is that normally the case for a file selection dialog?

**Comment by srjfoo** [comment]
> On Windows, the dialog is "modal", i.e. you can't do anything else in GG until you have closed the dialog. I'm guessing that isn't true on macOS. Is that normally the case for a file selection dialog?

This is literally the first time I've ever seen that behavior! Really raised my eyebrows! Perhaps @cpeel has an idea of what's going on.

**Comment by windymilla** [comment]
Related to this? https://github.com/python/cpython/issues/87821
Or this? https://github.com/python/cpython/issues/88991#issuecomment-1093924306
I don't know enough to know - just found those when searching for macOS, filedialog & modal

**Comment by srjfoo** [comment]
As far as I can tell, this is no longer happening.
