### ISSUE TITLE
GGprefs.json is being saved every "update" 

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#90]
Note to self: Probably something in the repeat timer is changing a pref, which causes a save of GGprefs.json.
May be related to Recent files

**Comment by tangledhelix** [comment]
I'm not sure if it's related, but I've been debugging a problem where GGprefs.json does not contain the RecentFiles. While running the app, the recent files list has a value (in memory, and shown in the app menu), but it never gets written out to disk, and therefore it doesn't persist between runs.

**Comment by tangledhelix** [comment]
Looks like you've already logged that issue as #91

**Comment by windymilla** [comment]
I'm not sure if the 2 issues are directly related or not.
